/* eslint-disable @typescript-eslint/no-explicit-any */
const IS_PRODUCTION: boolean = import.meta.env.PROD;
const AUTH_REDIRECT_URI: string = import.meta.env.VITE_AUTH0_REDIRECT_URI;

interface Environment {
  CLIENT_ID: string;
  CLIENT_SECRET: string;
  REALM: string;
  PROVIDER: string;
  REDIRECT_URI: string;
  ICLIENT_API_URL_QUERY: string;
  ICLIENT_API_URL_QUERY_PROCESS: string;
  IVITE_ISAAS_QUERY_PROCESS_SERVICE: string;
  IVITE_IPORTAL_STAFF_QUERY_PROCESS_SERVICE: string;
  ICLIENT_API_URL_PERSISTENCE_POST: string;
  IPORTAL_STAFF_QUERY_PROCESS_SERVICE: string;
  ISETTING_CREDICAR_QUERY_PROCESS_SERVICE: string;
  ISETTING_QUERY_PROCESS_SERVICE: string;
  ISAAS_PERSISTENCE_PROCESS_SERVICE: string;
  ISAAS_TOKEN_QUERY_PROCESS_SERVICE: string;
  TEMP_BUSINESS_UNIT: string;
  ICLIENT_API_URL_QUERY_USERS_PROCESS: string;
  AUTH0_DOMAIN: string;
  MAX_RETRIES_SERVICES: number;
  FETCH_TIMEOUT_SERVICES: number;
  MEDIA_QUERY_MOBILE: string;
  SECRET_KEY_PORTAL_ID: string;
  SECRET_KEY_PORTAL_NAME: string;
  IS_MOBILE_580: string;
  IS_MOBILE_743: string;
  IS_MOBILE_849: string;
  IS_MOBILE_970: string;
}

const enviroment: Environment = {
  CLIENT_ID: import.meta.env.VITE_AUTH0_CLIENT_ID,
  CLIENT_SECRET: import.meta.env.VITE_AUTH0_CLIENT_SECRET,
  REALM: import.meta.env.VITE_AUTH_REALM,
  PROVIDER: import.meta.env.VITE_AUTH_PROVIDER,
  REDIRECT_URI: IS_PRODUCTION ? window.location.origin : AUTH_REDIRECT_URI,
  ICLIENT_API_URL_QUERY: import.meta.env.VITE_ICLIENT_API_URL_QUERY,
  ICLIENT_API_URL_QUERY_PROCESS:
    import.meta.env.VITE_IUTILITIES_LINIX_CATALOGOS_GENERALES_API_URL_QUERY_PROCESS,
  IVITE_ISAAS_QUERY_PROCESS_SERVICE:
    import.meta.env.VITE_ISAAS_QUERY_PROCESS_SERVICE,
  IVITE_IPORTAL_STAFF_QUERY_PROCESS_SERVICE:
    import.meta.env.VITE_IPORTAL_STAFF_QUERY_PROCESS_SERVICE,
  ICLIENT_API_URL_PERSISTENCE_POST:
    import.meta.env.VITE_IUTILITIES_LINIX_CATALOGOS_GENERALES_API_URL_PERSISTENCE_PROCESS,
  IPORTAL_STAFF_QUERY_PROCESS_SERVICE:
    import.meta.env.VITE_IPORTAL_STAFF_QUERY_PROCESS_SERVICE,
  ISETTING_CREDICAR_QUERY_PROCESS_SERVICE:
    import.meta.env.VITE_ISETTING_CREDICAR_QUERY_PROCESS_SERVICE,
  ISETTING_QUERY_PROCESS_SERVICE:
    import.meta.env.VITE_ISETTING_QUERY_PROCESS_SERVICE,
  ISAAS_PERSISTENCE_PROCESS_SERVICE:
    import.meta.env.VITE_ISAAS_PERSISTENCE_PROCESS_SERVICE,
  ISAAS_TOKEN_QUERY_PROCESS_SERVICE:
    import.meta.env.VITE_ISAAS_TOKEN_QUERY_PROCESS_SERVICE,
  TEMP_BUSINESS_UNIT: "LINIX",
  ICLIENT_API_URL_QUERY_USERS_PROCESS:
    import.meta.env.VITE_IPRIVILEGES_LINIX_API_URL_QUERY_DATA_SERVICE,
  AUTH0_DOMAIN: import.meta.env.VITE_AUTH0_DOMAIN,
  MAX_RETRIES_SERVICES: Number(import.meta.env.VITE_MAX_RETRIES_SERVICES),
  FETCH_TIMEOUT_SERVICES: Number(import.meta.env.VITE_FETCH_TIMEOUT_SERVICES),
  MEDIA_QUERY_MOBILE: import.meta.env.VITE_MEDIA_QUERY_MOBILE,
  SECRET_KEY_PORTAL_ID: import.meta.env.VITE_SECRET_KEY_PORTAL_ID,
  SECRET_KEY_PORTAL_NAME: import.meta.env.VITE_SECRET_KEY_PORTAL_NAME,
  IS_MOBILE_580: import.meta.env.VITE_IS_MOBILE_580,
  IS_MOBILE_743: import.meta.env.VITE_IS_MOBILE_743,
  IS_MOBILE_849: import.meta.env.VITE_IS_MOBILE_849,
  IS_MOBILE_970: import.meta.env.VITE_IS_MOBILE_970,
};

export { enviroment };
